org: diegoribeiro
app: apollo-lambda
service: apollo-lambda
provider:
  name: aws
  runtime: nodejs16.x
  httpApi:
    cors: true
functions:
  graphql:
    handler: src/index.graphqlHandler 
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
      - websocket:
          route: $default
# Omit the following lines if you aren't using TS!
# plugins:
#   - serverless-plugin-typescript